//! macOS backend. AppKit has no clipboard-change notification, so we poll
//! `changeCount`, which is a cheap integer read. Every Mac clipboard tool
//! works this way.

use crate::{ClipboardChanged, Result};
use objc2::rc::autoreleasepool;
use objc2_app_kit::NSPasteboard;
use std::sync::mpsc::{self, Receiver};
use std::thread;
use std::time::Duration;

const POLL_INTERVAL: Duration = Duration::from_millis(250);

/// Pasteboard types from the nspasteboard.org convention that password
/// managers and similar apps use to mark content that must not be synced.
const EXCLUDED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

pub fn watch() -> Result<Receiver<ClipboardChanged>> {
    let (tx, rx) = mpsc::channel();
    thread::Builder::new()
        .name("clipboard-watcher".into())
        .spawn(move || {
            let mut last = change_count();
            loop {
                thread::sleep(POLL_INTERVAL);
                let now = change_count();
                if now != last {
                    last = now;
                    if tx.send(ClipboardChanged).is_err() {
                        break;
                    }
                }
            }
            tracing::debug!("clipboard watcher stopped");
        })?;
    Ok(rx)
}

fn change_count() -> isize {
    autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount())
}

pub fn is_excluded() -> bool {
    autoreleasepool(|_| {
        let Some(types) = NSPasteboard::generalPasteboard().types() else {
            return false;
        };
        types
            .iter()
            .any(|t| EXCLUDED_TYPES.contains(&t.to_string().as_str()))
    })
}
